export enum NsoErrorCode {
  F_TOKEN_FETCH_BAD_RESPONSE = 'F_TOKEN_FETCH_BAD_RESPONSE',
  F_TOKEN_FETCH_FAILED = 'F_TOKEN_FETCH_FAILED',
  ID_TOKEN_FETCH_BAD_RESPONSE = 'ID_TOKEN_FETCH_BAD_RESPONSE',
  ID_TOKEN_FETCH_FAILED = 'ID_TOKEN_FETCH_FAILED',
  NSO_APP_VERSION_BADLY_FORMATTED = 'NSO_APP_VERSION_BADLY_FORMATTED',
  NSO_APP_VERSION_FETCH_FAILED = 'NSO_APP_VERSION_FETCH_FAILED',
  REDIRECT_URI_WITHOUT_SESSION_TOKEN_CODE = 'REDIRECT_URI_WITHOUT_SESSION_TOKEN_CODE',
  SESSION_TOKEN_FETCH_BAD_RESPONSE = 'SESSION_TOKEN_FETCH_BAD_RESPONSE',
  SESSION_TOKEN_FETCH_FAILED = 'SESSION_TOKEN_FETCH_FAILED',
  USER_INFO_FETCH_BAD_RESPONSE = 'USER_INFO_FETCH_BAD_RESPONSE',
  USER_INFO_FETCH_FAILED = 'USER_INFO_FETCH_FAILED',
  WEB_API_CREDENTIAL_FETCH_BAD_RESPONSE = 'WEB_CREDENTIAL_FETCH_BAD_RESPONSE',
  WEB_API_CREDENTIAL_FETCH_FAILED = 'WEB_API_CREDENTIAL_FETCH_FAILED'
}

export class NsoError extends Error {
  constructor(message: string, public code: NsoErrorCode, public details: unknown = {}) {
    super(message);
  }
}
