export enum NsoErrorCode {
  NSO_APP_VERSION_FETCH_FAILED = 'NSO_APP_VERSION_FETCH_FAILED',
  NSO_APP_VERSION_BADLY_FORMATTED = 'NSO_APP_VERSION_BADLY_FORMATTED',
  REDIRECT_URI_WITHOUT_SESSION_TOKEN_CODE = 'REDIRECT_URI_WITHOUT_SESSION_TOKEN_CODE',
  SESSION_TOKEN_FETCH_FAILED = 'SESSION_TOKEN_FETCH_FAILED',
  SESSION_TOKEN_FETCH_BAD_RESPONSE = 'SESSION_TOKEN_FETCH_BAD_RESPONSE'
}

export class NsoError extends Error {
  constructor(message: string, public code: NsoErrorCode, public details: unknown = {}) {
    super(message);
  }
}
