export enum OuistitiErrorType {
  REQUIRED_PARAM = 'REQUIRED_PARAM',
  INVALID_ACTION = 'INVALID_ACTION',
  STRING_TOO_LONG = 'STRING_TOO_LONG',
  NUMBER_OUT_OF_RANGE = 'NUMBER_OUT_OF_RANGE',
  INVALID_ID = 'INVALID_ID',
  NICKNAME_TAKEN = 'NICKNAME_TAKEN',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  ORDER_ARRAY_INCOMPLETE = 'ORDER_ARRAY_INCOMPLETE'
}

export enum OuistitiInvalidActionReason {
  NOT_IN_LOBBY = 'NOT_IN_LOBBY',
  NOT_HOST = 'NOT_HOST'
}
