export enum OuistitiErrorType {
  REQUIRED_PARAM = 'REQUIRED_PARAM',
  STRING_TOO_LONG = 'STRING_TOO_LONG',
  INVALID_ID = 'INVALID_ID',
  NICKNAME_TAKEN = 'NICKNAME_TAKEN',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD'
}
