export enum OuistitiErrorType {
  HOST_CANNOT_KICK_SELF = 'HOST_CANNOT_KICK_SELF',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  INVALID_ACTION = 'INVALID_ACTION',
  INVALID_ID = 'INVALID_ID',
  INCORRECT_NUMBER_OF_PLAYERS = 'INCORRECT_NUMBER_OF_PLAYERS',
  NUMBER_OUT_OF_RANGE = 'NUMBER_OUT_OF_RANGE',
  ORDER_ARRAY_INCOMPLETE = 'ORDER_ARRAY_INCOMPLETE',
  PLAYER_DOESNT_HAVE_CARD = 'PLAYER_DOESNT_HAVE_CARD',
  REQUIRED_PARAM = 'REQUIRED_PARAM',
  STRING_TOO_LONG = 'STRING_TOO_LONG',
  VALUE_TAKEN = 'VALUE_TAKEN'
}

export enum OuistitiInvalidActionReason {
  BIDDING_FINISHED = 'BIDDING_FINISHED',
  GAME_ALREADY_STARTED = 'GAME_ALREADY_STARTED',
  GAME_NOT_STARTED = 'GAME_NOT_STARTED',
  NOT_HOST = 'NOT_HOST',
  NOT_IN_LOBBY = 'NOT_IN_LOBBY',
  NOT_PLAYERS_TURN = 'NOT_PLAYERS_TURN',
  PLAYER_IS_VACANT = 'PLAYER_IS_VACANT'
}
